# Site settings
title: Андрей Орлов, веб-разработчик
email: andyorlov@ya.ru
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://maibatsu.github.io/"
github_username: maibatsu
name: Andy Orlov
repository: maibatsu/maibatsu.github.io

# Build settings
port: 4000
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
sass:
  sass_dir: assets/_scss
  style: :compressed
